### ISSUE TITLE
Save filter settings between uses

### ISSUE THREAD

**Issue by AngleWyrm** [neitsa/PrepareLanding#13]
Once I have a favorite set of filters set up, I'd like the mod to remember them.

**Comment by neitsa** [comment]
Hi @AngleWyrm :) Thank you for your feature request!

Did you tried the latest versions? Since v0.4 (I know... it's only a few days since this release :p) you can load & save your filters (and even options). I closed issue #4 about this feature.

Did I misunderstood your request? Maybe you want something else than just a save / load feature?

**Comment by neitsa** [comment]
Hey @AngleWyrm :) Bumping the thread in case you missed it, I haven't got an answer and would like to know if I understood what you wanted correctly.

**Comment by neitsa** [comment]
Ofc, this can be reopened if something new is added to this conversation.
