### ISSUE TITLE
Only One Colony for each faction

### ISSUE THREAD

**Issue by Magichp** [neitsa/PrepareLanding#37]
Since the update to 1.1, when the mod is active, each faction only spawns a single colony on the world map, resulting in a quite empy world.

**Comment by neitsa** [comment]
Thank you very much for reporting the issue! I completely missed it :( I though I did touch the slider and so I didn't think it was a problem with the mod...

The mod didn't properly initialize the overall population during world generation which resulted in the minimum population being generated. It should be fixed with the latest release (on github and on steam)
